/* DADOS DO QUIZ — Descritores SAEB/SIMAVE (LP, 9º ano EF) */
const QUIZ_DADOS = {
  id: "saeb-descritores",
  titulo: "Treino SAEB/SIMAVE — Descritores de Leitura",
  descricao: "10 questões no formato da prova, cada uma treinando um descritor da matriz de Língua Portuguesa do 9º ano.",
  tempoPorQuestao: 90,
  questoes: [
    { pergunta: "AVISO: \"A reunião de pais acontecerá na quinta-feira, dia 18, às 19h, no pátio coberto da escola. Em caso de chuva, será transferida para a biblioteca.\" — Segundo o aviso, onde acontecerá a reunião se chover? (D1 — informação explícita)",
      opcoes: ["Na biblioteca", "No pátio coberto", "Na quadra", "Na sala dos professores"],
      correta: "Na biblioteca",
      explicacao: "D1 pede para LOCALIZAR uma informação que está escrita no texto: \"Em caso de chuva, será transferida para a biblioteca\"." },
    { pergunta: "\"A notícia da vitória se espalhou pela cidade como rastilho de pólvora.\" — A expressão destacada significa que a notícia se espalhou: (D3 — sentido de expressão)",
      opcoes: ["Muito rapidamente", "Causando destruição", "De maneira secreta", "Apenas entre poucas pessoas"],
      correta: "Muito rapidamente",
      explicacao: "D3 pede para INFERIR o sentido: o rastilho de pólvora queima veloz — a comparação indica rapidez." },
    { pergunta: "\"Pedro olhou pela janela, suspirou fundo e guardou de novo o convite na gaveta, pela terceira vez naquela semana.\" — Pode-se INFERIR que Pedro: (D4 — informação implícita)",
      opcoes: ["Está em dúvida se aceita o convite", "Perdeu o convite", "Já respondeu ao convite", "Nunca recebeu convite algum"],
      correta: "Está em dúvida se aceita o convite",
      explicacao: "D4: o texto não DIZ que ele está em dúvida, mas guardar o convite repetidas vezes, suspirando, deixa isso implícito." },
    { pergunta: "\"O plástico leva séculos para se decompor. Rios e oceanos recebem toneladas dele todos os dias. Animais marinhos confundem sacolas com alimento. Reduzir o consumo é urgente.\" — O TEMA do texto é: (D6 — tema)",
      opcoes: ["Os danos do plástico ao meio ambiente", "A alimentação dos animais marinhos", "A história do plástico", "O funcionamento dos oceanos"],
      correta: "Os danos do plástico ao meio ambiente",
      explicacao: "D6: o tema é o assunto central que costura todas as frases — aqui, o problema ambiental do plástico." },
    { pergunta: "\"Defendo que o celular pode ser um aliado em sala de aula. Com ele, o aluno pesquisa, traduz e acessa simulados em segundos.\" — A TESE do autor é: (D7 — tese)",
      opcoes: ["O celular pode ser um aliado em sala de aula", "O aluno pesquisa em segundos", "O celular traduz textos", "Os simulados são acessíveis"],
      correta: "O celular pode ser um aliado em sala de aula",
      explicacao: "D7: a tese é a OPINIÃO central que o autor defende; o restante são argumentos que a sustentam." },
    { pergunta: "\"Como as chuvas foram intensas durante toda a madrugada, o rio transbordou e alagou as ruas do centro.\" — A relação entre as orações é de: (D11 — causa e consequência)",
      opcoes: ["Causa e consequência", "Comparação", "Oposição", "Finalidade"],
      correta: "Causa e consequência",
      explicacao: "D11: as chuvas intensas (causa) provocaram o transbordamento (consequência) — relação marcada pelo \"como\"." },
    { pergunta: "\"— Que pintura caprichada! — disse a mãe, observando as manchas de tinta espalhadas pela parede inteira.\" — O efeito de sentido da fala da mãe é de: (D13 — ironia)",
      opcoes: ["Ironia", "Elogio sincero", "Medo", "Dúvida"],
      correta: "Ironia",
      explicacao: "D13: ela diz o contrário do que pensa — \"caprichada\" diante da bagunça é ironia, percebida pelo contraste com a cena." },
    { pergunta: "Qual das frases abaixo expressa uma OPINIÃO? (D14 — fato × opinião)",
      opcoes: [
        "O novo ginásio da escola é o mais bonito da região.",
        "O ginásio foi inaugurado em março de 2026.",
        "A quadra tem 40 metros de comprimento.",
        "Trezentas pessoas participaram da inauguração."
      ],
      correta: "O novo ginásio da escola é o mais bonito da região.",
      explicacao: "D14: \"o mais bonito\" é um julgamento pessoal (opinião); as outras frases trazem dados verificáveis (fatos)." },
    { pergunta: "\"Mariana estudou todos os dias durante o mês; ________, foi aprovada com a maior nota da turma.\" — O conectivo que expressa CONCLUSÃO é: (D15 — relações lógico-discursivas)",
      opcoes: ["portanto", "porém", "embora", "ou seja"],
      correta: "portanto",
      explicacao: "D15: \"portanto\" introduz a conclusão lógica do que foi dito antes. \"Porém\" indicaria oposição; \"embora\", concessão." },
    { pergunta: "\"Eu queria dizer que… bem… talvez… não sei se devo.\" — As reticências, nesse trecho, indicam: (D16 — efeitos da pontuação)",
      opcoes: ["Hesitação de quem fala", "Lista de itens", "Grito de raiva", "Fala de outra pessoa"],
      correta: "Hesitação de quem fala",
      explicacao: "D16: a pontuação produz sentido — aqui, as pausas das reticências mostram a dúvida e o nervosismo do falante." }
  ]
};
